apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.appName }}-images-pv"
  labels:
    type: local
  namespace: "{{ .Values.appName }}-ns"
spec:
  storageClassName: app-images-class
  capacity:
    storage: {{ .Values.backend.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.backend.storage.from }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "{{ .Values.appName }}-ns"
  name: "{{ .Values.appName }}-images-pvc"
spec:
  storageClassName: app-images-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.storage.capacity }}
