apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-backend-configmap"
  namespace: "{{ .Values.appName }}-ns"
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://pgpool:{{ .Values.database.accessPort }}/${POSTGRES_DB}"
  CORS-ALLOW-ORIGIN: "https://{{ .Values.frontend.url }}"
  MEDIA_IMAGES-STORAGE-PATH: {{ .Values.backend.storage.to }}
