apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-configs
  namespace: "{{ .Values.appName }}-ns"
data:
  pg_hba.conf: |
    host ${POSTGRES_DB} ${POSTGRES_REPLICATOR_USER} 0.0.0.0/0 md5