apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-init-config
  namespace: "{{ .Values.appName }}-ns"
data:
  01--init-create-replicator.sh: |
    #!/bin/bash
    set -e
    #Create the replicator user with replication privileges
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      DO \$\$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'replicator') THEN
          CREATE ROLE ${POSTGRES_REPLICATOR_USER} WITH REPLICATION LOGIN PASSWORD '${POSTGRES_REPLICATOR_PASSWORD}'';
        END IF;
      END;
      \$\$;
    EOSQL