apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: '{{ .Values.appName }}-db-replication-secret'
  namespace: '{{ .Values.appName }}-ns'
spec:
  encryptedData:
    POSTGRES_REPLICATOR_PASSWORD: AgCvVzPJD1CeQQ6IXh7xX7wPZg8fx0HeuOa3mc2cwxWG6WU12g/VuN20i/rEdaF/CbqLk7yqcX5qM0CYmN09hmEruD7VQtjArmP0NmklAjGuilCYWVxZqPuAsP9HZ1Ckn0ZWW27M3grpbOS2HoVL5KPPDs1hbM4AzHj7v2tM2D6IWB3haaG9bmnhNzu9CHk6D5xovE+NsU93WLhuwLsn0l/I89EXfQPeVBx8zKhOc1uJGE5VJ2gNBy9dhSifzwI+zKEhiMseXZxENkJSfZxOYKRRdkmJMsYYC5zNstZAF1MgbD1RsIMJv4qFGR8te8aurvkxB+q5nY8Y4AupFj6jaTNmXCqf8/0uhT90PIQW2tU+9va624jBfa0ThLEy7iUOY5+c1iCT97zQ2b+Hh9jDmczpnzlQe4rCz9aIZHRsBI9wfcxVQhJoseGsuIJ4wwknnsG9gl494KhCvLxTp8fv4RpyimD/ijr1b34MU/zv1N1Mo8L86Vp5zayrkLXIB8yC8uTgeT9SUiIkwM9kNb9JvKXONAyhc1JVJ1mBIOzWerboOVLyGQAbDzGDzr3wP3HZusK+1g++6IcCHlu6Wn6XJJeIZddlt4NkeEliBOU/gxMNIgP6STOQLySTYetADQTDRD3qRpyzINUSiCjsqrfmJuJ0c8TwItleRs3ef+rgucMeyGThu2CIuxtG6aQrvwJhBBkI721H78OAr8mxITyBNNhDkELFh22lkrs=
    POSTGRES_REPLICATOR_USER: AgBQ6hGMt3aWSxFUdhcY2rJPebvDCeEHILRE1Bl0vfXR6vVPF2wXWdchDtlbVXJlEsKSLC5X1tDDU3vHdmlHMBqG+6UxIVTDknk9TJrS+Ucye3f3la/qiNy6U+tnicSi+4SVoTlJa50I8bntvQoegOo/ZcUXCmzveeKYN7bo/M+9Swn7LaOSl3b4GNixPhftykyITwFz1zIAm8PBc/f3AUhtwSKnrMPP8giqQt39NR+HURHpZonvVHim1wThetXU24mCNqMPYRNokix1ML1PlBiWC+6XMUcLqR6hJtE/2B9lNp/TRK/a5vrC4mf13XAmJo6Ay3JsEzXGbtFsHSUQC/n+uu48BENOybbJqRMHrPQzRjuRSbhkqjOx6DsqAPenP8jmFb65uFaLfDJJgQIICOPc2tjQDfv0OFQ1572DYPnUYP1wdllk5twIF6Av5PpnCkOjReDbC1PheOBBssMzuTPi0SxczjA6zL+xdsAtoOjRQfNJcnUZliDqn4xOyHS0OUssOOfvMc3l2OF7+tPKa/IHvLUofDCBHfJX72kSMf7s5204zH6OgivLG4tw0dF6pbPM9fDWQPaPO2ZpT9WczibA7Eq6+6thR98DjyQvRHTNYfkUX+r4nNgMYQiMV447HJGua0+4wrITMbtaBTdSLpfxX+9sK3ytg8VOMzplv3TQr0LirS2paVHQ/OFVWu2qbyGOa11unzzvlMMdfzE5+IaDlg==
  template:
    metadata:
      creationTimestamp: null
      name: '{{ .Values.appName }}-db-replication-secret'
      namespace: '{{ .Values.appName }}-ns'
    type: Opaque

