apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-replication-script
  namespace: "{{ .Values.appName }}-ns"
data:
  replication-init.sh: |
    #!/bin/bash
    set -e

    #Clear any old data
    rm -rf /var/lib/postgresql/data/*

    echo "${POSTGRES_MASTER_HOST}:5432:*:${POSTGRES_REPLICATOR_USER}:${POSTGRES_REPLICATOR_PASSWORD}" > ~/.pgpass
    chmod 600 ~/.pgpass
    chown postgres:postgres ~/.pgpass
    chown -R postgres:postgres /var/lib/postgresql/data 
    chmod -R 750 /var/lib/postgresql/data 
    chown -R postgres:postgres /var/lib/postgresql/data/*
    chmod -R 750 /var/lib/postgresql/data/* 

    #Initialize replication
    pg_basebackup -h ${POSTGRES_MASTER_HOST} -D /var/lib/postgresql/data -U ${POSTGRES_REPLICATOR_USER} --wal-method=stream

    #Configure recovery
    echo "standby_mode = 'on'" > /var/lib/postgresql/data/postgresql.auto.conf
    echo "primary_conninfo = 'host=${POSTGRES_MASTER_HOST} port=5432 user=${POSTGRES_REPLICATOR_USER} password=${POSTGRES_REPLICATOR_PASSWORD}'" >> /var/lib/postgresql/data/postgresql.auto.conf
    echo "recovery_target_timeline = 'latest'" >> /var/lib/postgresql/data/postgresql.auto.conf

    #Start PostgreSQL
    su -c "exec postgres" -s /bin/bash postgres