apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-sc-deployment
  labels:
    app: frontend-sc-deployment
  namespace: "{{ .Values.appName }}-ns"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-sc-deployment
  template:
    metadata:
      labels:
        app: frontend-sc-deployment
    spec:
      containers:
      - name: sc-frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.imageTag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-frontend-service"
  namespace: "{{ .Values.appName }}-ns"
spec:
  type: NodePort
  selector:
    app: frontend-sc-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
